### ISSUE TITLE
Provide a `auth.json` example

### ISSUE THREAD

**Issue by fubarhouse** [crabvk/bar-protonmail#1]
`auth.json` is expected to be `json` and in my case it was not.
It might be useful for others to realise `auth.json` should be formatted as such:

```
{
    "UID": "your-uid",
    "AccessToken": "valid access token"
}
```

**Comment by crabvk** [comment]
Could you please tell what was the content of auth.json in your case? I never noticed `AUTH-...` values other than url-encoded json with UID and AccessToken.

**Comment by fubarhouse** [comment]
In my case, I copied the plain text string "wubiefsidn2342342vksdfmvpsldmflvcs1241t345e" (example).
`auth.json` just contained that as a string, unformatted json.

Probably the wrong thing to copy but an example could be helpful.

**Comment by crabvk** [comment]
What if `save_auth.py` will validate the value before write auth.json and show an error when the value doesn't have UID or AccessToken?

**Comment by fubarhouse** [comment]
That would be best - some sort of indication to show if the value saved is correctly formatted and valid.
It could also help if `save_auth.py` actually performed a test to the API using the credentials.
