### ISSUE TITLE
Not sure if it was just me, or something else is wrong...

### ISSUE THREAD

**Issue by ghost** [crabvk/bar-protonmail#10]
I just did a reinstall of my linux laptop and when I was grabbing this the changes here:

https://github.com/crabvk/bar-protonmail/commit/8e280f614c4969556078e92a78551978b5bb70ba

did not show up, it still had the old values, and I had to go in and manually edit the file to make it work. Like I said I'm not sure if it is something I did wrong or, if it isn't actually showing up when you do the `pip install bar-protonmail` command. Just wanted to let ya know in case there is an issue so you can fix it. :)

**Comment by crabvk** [comment]
Good catch, thanks.
I forgot to upload the new version (1.0.2) to pypi.org. But [having the git-repo dependency](https://github.com/crabvk/bar-protonmail/blob/39a3ca4d278d438990830923e907661cb02154fa/pyproject.toml#L23) of proton-client does not allow the package to be published anyway (due to security concerns I guess).
Gonna fix the installation process in the readme, can't use pip anymore.

**Comment by ghost** [comment]
Ah ok, I had to re-read that (still early here *yawn*) I was gonna say I just used `pip` yesterday to install it, but I understand now that you meant you can't publish it with that dependency. If it helps I just did `pip install bcrypt python-gnupg pyopenssl` and then `pip3 install https://github.com/ProtonMail/proton-python-client/archive/refs/tags/0.7.1.zip` and was able to do `pip install bar-protonmail ` (Not sure if you may just want to include that in the read me, it may allow you to upload it then?)

**Comment by crabvk** [comment]
Packages on pypi.org can't have file dependency either. And I don't want to exclude proton-client from the list of deps with instruction to install it manually, this will lead to other issues.

**Comment by ghost** [comment]
Ah ok, I am still very new (and learning github) so I wasn't sure if that would be allowed or not.
