### ISSUE TITLE
how does bar-protonmail store user credentials?

### ISSUE THREAD

**Issue by ItsTerm1n4l** [crabvk/bar-protonmail#11]
Hi, I was wondering where and how bar-protonmail stores my credentials (email address and password)?
I have finally found a script to show my unread emails, Thank you.

**Comment by iamtalhaasghar** [comment]
The [script asks for username / password](https://github.com/crabvk/bar-protonmail/blob/ba003e5bff7b876111a1dd68797a5350ff8f2785/bar_protonmail/auth.py#L14) when run for the very first time and then creates a `session.json` and [uses session keys / tokens](https://github.com/crabvk/bar-protonmail/blob/ba003e5bff7b876111a1dd68797a5350ff8f2785/bar_protonmail/__init__.py#L34) from settings.json onwards.

As of now and per my understanding your account password is not stored anywhere. But still be very careful and not share `settings.json` with any one and don't upload it on internet.

**Comment by crabvk** [comment]
Your session, cache and log are stored in *~/.cache/bar-protonmail*. Email and password are not stored, they are exchanged for `AccessToken` (see *session.json*).

**Comment by ItsTerm1n4l** [comment]
Ok thank you, I found session.json earlier and couldnt find my credentials, I wasnt sure if they were stored somewhere else or if access tokens were used anddidnt know how secure this script was.
closing issue.
