### ISSUE TITLE
updated protonmail module for waybar/i3blocks/polybar/yabar

### ISSUE THREAD

**Issue by servusdei2018** [crabvk/bar-protonmail#2]
Hi! I stumbled across this today since I recently switched to waybar and was wondering if there was a ProtonMail module for it, and found your repository. I tinkered around with it for a while, but ultimately wasn't able to find the AUTH token and refresh token mentioned in the README so I decided to [make my own](https://github.com/servusdei2018/protoncheck) since it appeared that this method had been deprecated. 

I did some research and found an official ProtonMail library, and used it to make mine. It works with waybar, i3blocks, polybar, and yabar, and, given your email and password, checks the amount of unread emails in your ProtonMail inbox. I just thought I'd let you know, since your work inspired me and without seeing it I wouldn't have gotten the impetus to go and look into making my own. Thank you 😃

**Comment by crabvk** [comment]
You are welcome 🙂

**Comment by crabvk** [comment]
I made an update to bar-protonmail and now it uses official [proton-client](https://github.com/ProtonMail/proton-python-client) python library. No need to get tokens from a browser anymore.
