### ISSUE TITLE
Is it possible to hide the module when there are no notifications? [Polybar]

### ISSUE THREAD

**Issue by CT-66** [crabvk/bar-protonmail#3]
Is it possible to hide the module when there are no new emails in the inbox?  

Thanks!

**Comment by crabvk** [comment]
No, it's not possible. I think it is useful to show the badge even without unread inbox messages, because you can open Inbox by clicking on the badge.

**Comment by CT-66** [comment]
I agree it's useful to open the inbox quickly, but I think there should be an option to hide it if there are no notifications. Maybe it could be configured using an environment variable?
