### ISSUE TITLE
Message sound repeats itself for almost everything

### ISSUE THREAD

**Issue by ghost** [crabvk/bar-protonmail#6]
Every time I write a message, delete a message, move a message Etc. the sound I am using for messages goes off. Including (since I have the interval set to 10) going off every 10 seconds while I am writing a new message. Is there a way (other than changing the interval) to make it only sound when you receive a new message to your inbox? I am sure it is something simple that I just haven't figured out yet, but wanted to make sure I wasn't just missing something. In case this part matters, I am using polybar with the module looking like this:

[module/protonmail]
type = custom/script
exec = bar-protonmail -f polybar -b "%{F#8A2BFF}%{T2}%{T-}%{F-} %{T1}" -s message-new-instant
interval = 10
click-left = xdg-open https://mail.protonmail.com/u/0/inbox

**Comment by crabvk** [comment]
This is a bug, I didn't test sound feature enough before.

**Comment by ghost** [comment]
Is it a bug that you might fix in the future, or may know how to fix? :)

**Comment by crabvk** [comment]
Gonna fix it today, or tomorrow.

**Comment by ghost** [comment]
Sweet thank you so much, I am using both your Gmail and this module too, I love them both... Thanks for the GREAT work!

**Comment by ghost** [comment]
![2022-11-28_16-59](https://user-images.githubusercontent.com/93161870/204390095-290b03b9-02b1-45c9-8160-ef84b8706001.png)

Also, I noticed from time to time I get this in the module as well... But I just thought it was because of the refresh interval being so close together ? (The White envelope is the next module, the gmail one, I just wanted to make sure I caught the entire "error")

**Comment by crabvk** [comment]
Can't reproduce the DBus error. It must be from `notify-send` program from [here](https://github.com/crabvk/bar-protonmail/blob/56c4b00af252bcca92336ad350077f45949eb115/bar_protonmail/output.py#L66).
Feel free to reopen this issue or create a new one if you find instructions how to reproduce that error.
