### ISSUE TITLE
Weird Error when receiving new mail

### ISSUE THREAD

**Issue by ghost** [crabvk/bar-protonmail#9]
![2022-12-09_08-53](https://user-images.githubusercontent.com/93161870/206717976-ffd0fb8e-ad10-4d5e-b274-648e4198ad74.png)

Everytime I get a new email I get the following error on polybar, it goes away with the next interval (10 seconds) and returns to the icon and number format. But it happens with every new email. I have not changed the scripts and the following is the module setup I am using in Polybar:

[module/protonmail]
type = custom/script
exec = bar-protonmail -f polybar -b "%{F#8A2BFF}%{T2}%{T-}%{F-} %{T1}" -s message-new-instant
interval = 10
click-left = xdg-open https://mail.protonmail.com/u/0/inbox

I have tried without the font and color modifiers and it still happens, so I am not sure what else to try.

**Comment by CerealKiller-John** [comment]
And it has gone back to notifying me when I delete mail and the number changes on the bar to a lesser amount as well.

**Comment by crabvk** [comment]
It might be something wrong with your notification daemon. Because bar-protonmail just calls `notify-send` command from libnotify package.
What notification daemon are you using? (or what distro/DE)

**Comment by ghost** [comment]
> What notification daemon are you using? (or what distro/DE)

Base is Fedora Workstation 37 w/ Gnome DE. But I then installed BSPWM with Polybar from there and am using it.

**Comment by crabvk** [comment]
Try to execute `notify-send message`, does it show a notification?

**Comment by ghost** [comment]
> Try to execute `notify-send message`, does it show a notification?

I did in the terminal and it gave me the same error "GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable"

**Comment by crabvk** [comment]
OK, so there's something wrong with your notification daemon, I guess.
I'll add a CLI flag to disable notifications in next release, so keeping the issue open until then.

**Comment by ghost** [comment]
OK, thank you, do you have an estimated time of the next release, just wondering.

**Comment by crabvk** [comment]
Today, I guess.

**Comment by ghost** [comment]
Sweet, thank you. Keep up the great work!

**Comment by ghost** [comment]
Oh, and I forgot to ask, the flag will just disable the text spitout right, like I will still get updated when I receive a new email, correct?

**Comment by crabvk** [comment]
It'll disable executing `notify-send`.

**Comment by ghost** [comment]
> 


> It'll disable executing `notify-send`.

I figured out what my issue was, I had to install `dunst`, I forgot to install it again when I was doing my reinstall. So I guess there is no need to disable `notify-send` but maybe put `dunst` on the read me list for notifications or something like that?

**Comment by crabvk** [comment]
Good to hear you fixed it :)
Have added a note about notification daemon in readme.
Disable notifications flag might be useful though, for those who get lots of emails.

**Comment by ghost** [comment]
True I wasn't thinking about that, and flags are optional too so it's up to the end user. :)
